Identificacion de Imagenes con Redes Neuronales

Grupo 2:

- Esteban Daniel Pereira Nuñez
- Maria Bernarda Serrano Larrea
- Damaris Raquel Terrazas Teran
- Oscar Enrique Ibañez Siñani

Librerias
- pip install opencv-contrib-python
- pip install tensorflow (actualmente se requiere Python 3.7)
- pip install matplotlib
- pip install tqdm
- pip install numpy
- pip install pickle

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm

In [2]:
DATADIR = "testData"

CATEGORIES = ["Dog", "Cat"]

IMG_SIZE = 100

training_data = []

def create_training_data():
    for category in CATEGORIES:

        path = os.path.join(DATADIR,category) 
        class_num = CATEGORIES.index(category)  # clasificamos los resultados (un 0 o un 1). 0=dog 1=cat

        for img in tqdm(os.listdir(path)):  # pasamos por cada imagen
            try:
                img_array = cv2.imread(os.path.join(path,img) ,cv2.IMREAD_GRAYSCALE)  # convertimos las imagenes en arrays
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))  # ajustamos el tamaño de las imagenes
                training_data.append([new_array, class_num])  # añadimos la imagen a la lista de datos de muestra
            except Exception as e: 
                pass

create_training_data()

print(len(training_data))

100%|█████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 187.55it/s]12



In [3]:
import random

random.shuffle(training_data)

for sample in training_data[:10]:
    print(sample[1])

0
0
1
0
1
1
0
1
0
1


In [4]:
X = []
y = []

for features,label in training_data:
    X.append(features)
    y.append(label)

print(X[0].reshape(-1, IMG_SIZE, IMG_SIZE, 1))

X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1)

[[[[127]
   [102]
   [130]
   ...
   [172]
   [171]
   [183]]

  [[117]
   [123]
   [160]
   ...
   [155]
   [166]
   [167]]

  [[106]
   [132]
   [151]
   ...
   [117]
   [118]
   [139]]

  ...

  [[166]
   [ 88]
   [150]
   ...
   [115]
   [107]
   [117]]

  [[111]
   [175]
   [145]
   ...
   [103]
   [105]
   [ 98]]

  [[173]
   [134]
   [156]
   ...
   [141]
   [111]
   [ 93]]]]


In [5]:
import pickle

pickle_out = open("test_X.pickle","wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("test_y.pickle","wb")
pickle.dump(y, pickle_out)
pickle_out.close()

pickle_in = open("test_X.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("test_y.pickle","rb")
y = pickle.load(pickle_in)